package main

import "fmt"

func main() {
	//word1 := "ymbgaraibkfmvocpizdydugvalagaivdbfsfbepeyccqfepzvtpyxtbadkhmwmoswrcxnargtlswqemafandgkmydtimuzvjwxvlfwlhvkrgcsithaqlcvrihrwqkpjdhgfgreqoxzfvhjzojhghfwbvpfzectwwhexthbsndovxejsntmjihchaotbgcysfdaojkjldprwyrnischrgmtvjcorypvopfmegizfkvudubnejzfqffvgdoxohuinkyygbdzmshvyqyhsozwvlhevfepdvafgkqpkmcsikfyxczcovrmwqxxbnhfzcjjcpgzjjfateajnnvlbwhyppdleahgaypxidkpwmfqwqyofwdqgxhjaxvyrzupfwesmxbjszolgwqvfiozofncbohduqgiswuiyddmwlwubetyaummenkdfptjczxemryuotrrymrfdxtrebpbjtpnuhsbnovhectpjhfhahbqrfbyxggobsweefcwxpqsspyssrmdhuelkkvyjxswjwofngpwfxvknkjviiavorwyfzlnktmfwxkvwkrwdcxjfzikdyswsuxegmhtnxjraqrdchaauazfhtklxsksbhwgjphgbasfnlwqwukprgvihntsyymdrfovaszjywuqygpvjtvlsvvqbvzsmgweiayhlubnbsitvfxawhfmfiatxvqrcwjshvovxknnxnyyfexqycrlyksderlqarqhkxyaqwlwoqcribumrqjtelhwdvaiysgjlvksrfvjlcaiwrirtkkxbwgicyhvakxgdjwnwmubkiazdjkfmotglclqndqjxethoutvjchjbkoasnnfbgrnycucfpeovruguzumgmgddqwjgdvaujhyqsqtoexmnfuluaqbxoofvotvfoiexbnprrxptchmlctzgqtkivsilwgwgvpidpvasurraqfkcmxhdapjrlrnkbklwkrvoaziznlpor"
	//word2 := "qhxepbshlrhoecdaodgpousbzfcqjxulatciapuftffahhlmxbufgjuxstfjvljybfxnenlacmjqoymvamphpxnolwijwcecgwbcjhgdybfffwoygikvoecdggplfohemfypxfsvdrseyhmvkoovxhdvoavsqqbrsqrkqhbtmgwaurgisloqjixfwfvwtszcxwktkwesaxsmhsvlitegrlzkvfqoiiwxbzskzoewbkxtphapavbyvhzvgrrfriddnsrftfowhdanvhjvurhljmpxvpddxmzfgwwpkjrfgqptrmumoemhfpojnxzwlrxkcafvbhlwrapubhveattfifsmiounhqusvhywnxhwrgamgnesxmzliyzisqrwvkiyderyotxhwspqrrkeczjysfujvovsfcfouykcqyjoobfdgnlswfzjmyucaxuaslzwfnetekymrwbvponiaojdqnbmboldvvitamntwnyaeppjaohwkrisrlrgwcjqqgxeqerjrbapfzurcwxhcwzugcgnirkkrxdthtbmdqgvqxilllrsbwjhwqszrjtzyetwubdrlyakzxcveufvhqugyawvkivwonvmrgnchkzdysngqdibhkyboyftxcvvjoggecjsajbuqkjjxfvynrjsnvtfvgpgveycxidhhfauvjovmnbqgoxsafknluyimkczykwdgvqwlvvgdmufxdypwnajkncoynqticfetcdafvtqszuwfmrdggifokwmkgzuxnhncmnsstffqpqbplypapctctfhqpihavligbrutxmmygiyaklqtakdidvnvrjfteazeqmbgklrgrorudayokxptswwkcircwuhcavhdparjfkjypkyxhbgwxbkvpvrtzjaetahmxevmkhdfyidhrdeejapfbafwmdqjqszwnwzgclitdhlnkaiyldwkwwzvhyorgbysyjbxsspnjdewjxbhpsvj"
	//word1 := "a"
	//word2 := "aa"
	//word1 := "ddaabic"
	//word2 := "cbaaaddi"
	word1 := "njidfxzclwnkpygnebpqefwvpozjleyhbivilphmnmbhdscblhhawjmhijutmuwzafkzkemgqzfuvkoabjwhlfcqovmehirwxlhpojcurpaihbhlxsjtidyflfhpfboxtcfupdpapovcclpjepejihugzdeyewjkomterbfopznalawzvafwmdhdvohjkxkkxtahaogrgegwhzvkwofeubtxwjblfgcjmcgngyfkbmchlwmwyzymzhssetekazyjuawxrwgtvvukifbhffcsmchqrbzfccilaqukxwhhmgnrjfdxcuxudgloezqefmycoumjtvmxkfjerurgpfidptfzhfxqhvmteoitbhjkwahcwjlhkdqxxjeqzhqfmbpjbajeuatyvrtniefebfqxrcqytoiamnksnhejglcrbrrdvzqetinhcgitcpecmjlooooyyverjcbyyutblladoczzpklaywjnuzpfxefkeexfqqhzmkrzcremeyvankabyfqrozjgyarkbaqolgbpxlhrvajbnjrtjnobwharstxwyzalgtrtzefnrsvnteiamxfiqqqlaqxonunmjatgvuzcvndwpnplopfklohenlhgotdbpspzotfwlnqaazinzbvpkmloykyuljnxxblvstyakcpkzcfbtgownhmfnectmvkwsofbsngiprrshlaguetvlmsmkfskgtifuhkugcntmlobxmwvgwkynywvpbulegaiapxlgebjwwrwbhhflpcpgbzfjxzxvgalxisrpnykjoitlwkmkywmtgvtvgtvjzgohaqldsvjrqauhpmrhltcrlkcobmzxhfugcunxczdnrzuvbfpvxqlcqvhrfbemkkwswgqlzewqvjxdywdwugrdc"
	word2 := "lgifjgbrfazhaujnjbzqcqclfwmvqjbntlaxolsyjgtgklahfdlegfdlqkvkellejmlpohiwrfwpvhlaypbcagwkyjglfpjgrbwmqwykoahpetoaxzggqpwirmblbxeyuwqkhzrqmlylexfklpeaufalmqtraexftbvewchnampxclakqwttafmxynrlfpojpzvqeruswburgvmyknordokqfvbmwhyethtjhngxutdcvczkfwhtzxrpycgrlwuefabbnibksmmqwpbjsqdcziwclluocegczmoexxjrcoabozggdtatdurhtvgldnkfvexomtxglywxnifbalheijsghpefhyrlnknihhwbfrwoojjhjnzhwtwyqhxkmputfowruheyfcvgzvinmoeahamzcxjhavkclwnhvakbcvsbcjpxujlhfrhnhouxzrlkcufjktpvwfgktvtmaemuubhvlpkzzhqloofxzxrebvxmyuoakufuykyiqbvguujncoblnpgolcsmsorhcagncpzsaadxmzdzuzlqfbrknpextenhvyishkiqibbgfxkbjjmyeizpwzmeirthzlhscykgohudjobiwjtgcdncyjffivgdzncmbepatmdtvcvwczmmvzpdysvekeleoiomyyfdjjkxnmkwfohrqapbjyaohjghtqcwtkpseolfshewvkaazwchrjdrlbzcdenyhbfxpsuieweunmbfprwwzfjhbhipbnobeqobttpadtftjtfegjlcntncqhpqfmqwpfxomxpfxekevzfgicblxnytjkcedrlamtklgcrvvaxwnjgavrsmkarjzzzlgfxgufhewqvmvgohtsyxriuzwnalpuifncquknvtzrwpkqrjvzomisp"

	fmt.Println(findTheDifference(word1, word2))

}

func findTheDifference(s string, t string) string {
	//concat string
	statement := s + t
	length := len(s + t)
	//create map of unique values
	flags := map[string]bool{}

	i := 0
	for j := range statement {
		if !flags[string(statement[j])] {
			flags[string(statement[j])] = true
			statement = statement + string(statement[j])
			i++

		}
	}
	//slice the string to save the not repeated value
	//statement = statement[length+len(s):]
	if i > 1 {
		statement = statement[length:]

	}
	// else {
	// 	statement = statement[length:]

	// }
	fmt.Println(len(statement))

	//return byte(statement[0])
	return statement

}
